version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket artefact-storage --output-template-file serverlessoutput.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - serverlessoutput.yaml